app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'FrontController@index');

Route::get('listarProductos/{id_categoria}','FrontController@listarProductos');

Route::get('showProducto/{id_producto}','FrontController@showProducto');

Route::post('addCart','FrontController@addCart');

Route::get('detalleCompra','FrontController@detalleCompra');

Route::get('eliminarProducto/{idRow}','FrontController@eliminarProducto');

Route::group(['middleware' => ['auth']], function(){
	Route::get('finalizarCompra','FrontController@finalizarCompra');

	Route::get('verCompras','FrontController@verCompras');
});



/*------------Rutas para login comite------------*/
Route::get('auth/login', 'LoginController@showLogin'); // Mostrar el formulario de login

Route::post('auth/login', 'LoginController@postLogin'); // Verificar datos

Route::get('auth/logout', 'LoginController@logOut'); // Finalizar sesión

Route::resource('usuarios','UsuarioController');

Route::group(['prefix' => 'administrador','middleware' => 'auth'], function(){
	Route::resource('categoria', 'CategoriaController');
	Route::resource('producto', 'ProductoController');
	Route::get('home',function(){
		return view('administrador.inicio');
	});
});

resources/views/administrador/createCategoria.blade.php
	@extends('administrador.masterAdmin')
	@section('content')
		<div class="row">
        	<div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Registrar <small>Categorias</small></h2>
                  </div>
                  <div class="x_content">
                   <br />
                   
                    {!! Form::open(['url' => 'administrador/categoria','class'=>'form-horizontal form-label-left']) !!}

                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Nombre Categoria
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          {!! Form::text('nombre',null,['class'=>'form-control col-xs-12 col-md-7'])!!}
                          
                        </div>
                      </div>
                     
                      <div class="ln_solid"></div>
                      <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                          <a href="{{url('administrador')}}" class="btn btn-primary">Cancelar</a>
                          <button type="submit" class="btn btn-success">Enviar</button>
                        </div>
                      </div>

                    {!! Form::close() !!}
                  </div>
                </div>
            </div>
    	</div>
	@stop
	@section('scripts')
		@if(Session::has('mensaje'))
  		<?php $mensaje=Session::get('mensaje');?>

  		<script>
    		var mensaje="<?php echo $mensaje; ?>";
    		new PNotify({
    			title: 'Correcto',
    			text: mensaje,
    			type: 'success'
			});
    	</script>
    	@endif
	@stop

resources/views/administrador/createProducto.blade.php
	@extends('administrador.masterAdmin')
	@section('content')
		<div class="row">
        	<div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Registrar <small>Productos</small></h2>
                  </div>
                  <div class="x_content">
                   <br />
                   
                    {!! Form::open(['url' => 'administrador/producto','class'=>'form-horizontal form-label-left','files' => true]) !!}

                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Nombre Producto
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          {!! Form::text('nombre',null,['class'=>'form-control col-xs-12 col-md-7'])!!}
                        </div>
                      </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Categorias
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          <select name="id_categoria" class="form-control col-xs-12 col-md-7">
                            <option value="0">Seleccione una opcion</option>
                            @foreach($categorias as $categoria)
                              <option value="{{$categoria->id_categoria}}">{{$categoria->nombre}}</option>
                            @endforeach
                          </select>
                        </div>
                      </div>
                    

                     <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Precio
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          {!! Form::text('precio',null,['class'=>'form-control col-xs-12 col-md-7'])!!}
                        </div>
                      </div>
  
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Cantidad
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          {!! Form::text('cantidad',null,['class'=>'form-control col-xs-12 col-md-7'])!!}
                        </div>
                      </div>

                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Imagen
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          {!! Form::file('imagen',null,['class'=>'form-control col-xs-12 col-md-7'])!!}
                        </div>
                      </div>

                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Descripción
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          {!! Form::textarea('descripcion',null,['class'=>'form-control col-xs-12 col-md-7'])!!}
                        </div>
                      </div>

                      <div class="ln_solid"></div>
                      <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                          <a href="{{url('administrador')}}" class="btn btn-primary">Cancelar</a>
                          <button type="submit" class="btn btn-success">Enviar</button>
                        </div>
                      </div>

                    {!! Form::close() !!}
                  </div>
                </div>
            </div>
    	</div>
	@stop
	@section('scripts')
		@if(Session::has('mensaje'))
  		<?php $mensaje=Session::get('mensaje');?>

  		<script>
    		var mensaje="<?php echo $mensaje; ?>";
    		new PNotify({
    			title: 'Correcto',
    			text: mensaje,
    			type: 'success'
			});
    	</script>
    	@endif
	@stop

resources/views/administrador/editCategoria.blade.php
@extends('administrador.masterAdmin')

@section('content')

	<div class="row">
        	<div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Registrar <small>Categorias</small></h2>
                  </div>
                  <div class="x_content">
                   <br />
                   	{!! Form::model($categoria,['action' =>['CategoriaController@update',$categoria->id_categoria],'class'=>'form-horizontal form-label-left','method'=>'PUT']) !!}

                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Nombre Categoria
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          {!! Form::text('nombre',null,['class'=>'form-control col-xs-12 col-md-7'])!!}
                          
                        </div>
                      </div>
                     
                      <div class="ln_solid"></div>
                      <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                          <a href="{{url('administrador')}}" class="btn btn-primary">Cancelar</a>
                          <button type="submit" class="btn btn-success">Enviar</button>
                        </div>
                      </div>

                    {!! Form::close() !!}
                  </div>
                </div>
            </div>
    	</div>
@stop

resources/views/administrador/editProducto.blade.php
	@extends('administrador.masterAdmin')
	@section('content')
		<div class="row">
        	<div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Editar <small>Productos</small></h2>
                  </div>
                  <div class="x_content">
                   <br />
                   
                    {!! Form::model($producto,['action' =>['ProductoController@update',$producto->id_producto],'class'=>'form-horizontal form-label-left','method'=>'PUT']) !!}

                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Nombre Producto
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          {!! Form::text('nombre',null,['class'=>'form-control col-xs-12 col-md-7'])!!}
                        </div>
                      </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Categorias
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          {!! Form::select('id_categoria', $categorias, $producto->id_categoria,['class'=>'form-control col-xs-12 col-md-7']) !!}
                          
                        </div>
                      </div>
                    

                     <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Precio
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          {!! Form::text('precio',null,['class'=>'form-control col-xs-12 col-md-7'])!!}
                        </div>
                      </div>
  
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Cantidad
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          {!! Form::text('cantidad',null,['class'=>'form-control col-xs-12 col-md-7'])!!}
                        </div>
                      </div>

                      

                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Descripción
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          {!! Form::textarea('descripcion',null,['class'=>'form-control col-xs-12 col-md-7'])!!}
                        </div>
                      </div>

                      <div class="ln_solid"></div>
                      <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                          <a href="{{url('administrador')}}" class="btn btn-primary">Cancelar</a>
                          <button type="submit" class="btn btn-success">Enviar</button>
                        </div>
                      </div>

                    {!! Form::close() !!}
                  </div>
                </div>
            </div>
    	</div>
	@stop
	@section('scripts')
		@if(Session::has('mensaje'))
  		<?php $mensaje=Session::get('mensaje');?>

  		<script>
    		var mensaje="<?php echo $mensaje; ?>";
    		new PNotify({
    			title: 'Correcto',
    			text: mensaje,
    			type: 'success'
			});
    	</script>
    	@endif
	@stop

resources/views/administrador/indexCategorias.blade.php
@extends('administrador.masterAdmin')

@section('content')
	<div class="col-md-10 col-md-offset-1 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Lista de categorias</h2>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
					@if(count($categorias)!=0)
                    <table class="table table-striped">
                      <thead>
                        <tr>
                          <th>#</th>
                          <th>Nombre </th>
                          <th>Editar</th>
                          <!--<th>Eliminar</th>-->
                        </tr>
                      </thead>
                      <tbody>
                      @foreach($categorias as $categoria)
                        <tr>
                          <th scope="row">{{$categoria->id_categoria}}</th>
                          <td>{{$categoria->nombre}}</td>
                          <td><a href="{{route('administrador.categoria.edit',$categoria->id_categoria)}}" class="btn btn-primary">Actualizar</a></td>
                          <!--<td><a href="{{route('administrador.categoria.edit',$categoria->id_categoria)}}" class="btn btn-danger">Eliminar</a></td>-->
                        </tr>
                       @endforeach
                      </tbody>
                    </table>
                    {!! $categorias->render() !!}
                    @endif

                  </div>
                </div>
              </div>

              <div class="clearfix"></div>
@stop
@section('scripts')
    @if(Session::has('mensaje'))
      <?php $mensaje=Session::get('mensaje');?>

      <script>
        var mensaje="<?php echo $mensaje; ?>";
        new PNotify({
          title: 'Correcto',
          text: mensaje,
          type: 'success'
      });
      </script>
      @endif
  @stop

resources/views/administrador/indexProductos.blade.php
@extends('administrador.masterAdmin')

@section('content')
	<div class="col-md-10 col-md-offset-1 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Lista de productos</h2>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
					@if(count($productos)!=0)
                    <table class="table table-striped">
                      <thead>
                        <tr>
                          <th>#</th>
                          <th>Nombre </th>
                          <th>precio</th>
                          <th>Cantidad</th>
                          <th>Descripcion</th>
                          <th>Imagen</th>
                          <th>Editar</th>
                          <!---<th>Eliminar</th>-->
                        </tr>
                      </thead>
                      <tbody>
                      @foreach($productos as $producto)
                        <tr>
                          <th scope="row">{{$producto->id_producto}}</th>
                          <td>{{$producto->nombre}}</td>
                          <td>${{$producto->precio}}</td>
                          <td>{{$producto->cantidad}}</td>
                          <td>{{$producto->descripcion}}</td>
                          <td><img src="{{asset('imagenes')}}/{{$producto->imagen}}" width="50" height="50" class="img-responsive"></td>
                          <td><a href="{{route('administrador.producto.edit',$producto->id_producto)}}" class="btn btn-primary">Actualizar</a></td>
                          <!--<td><a href="{{route('administrador.categoria.edit',$producto->id_producto)}}" class="btn btn-danger">Eliminar</a></td>-->
                        </tr>
                       @endforeach
                      </tbody>
                    </table>
                    {!! $productos->render() !!}
                    @endif

                  </div>
                </div>
              </div>

              <div class="clearfix"></div>
@stop
@section('scripts')
    @if(Session::has('mensaje'))
      <?php $mensaje=Session::get('mensaje');?>

      <script>
        var mensaje="<?php echo $mensaje; ?>";
        new PNotify({
          title: 'Correcto',
          text: mensaje,
          type: 'success'
      });
      </script>
      @endif
  @stop

resources/views/administrador/inicio.blade.php
@extends('administrador.masterAdmin')

@section('content')
	Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque, distinctio libero! Neque est modi reiciendis, repellendus ab velit pariatur perferendis deleniti necessitatibus inventore similique, architecto vero veniam eveniet voluptas nulla.
@stop

resources/views/administrador/masterAdmin.blade.php
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Administrador</title>

    <link rel="stylesheet" href="{{asset('assets/css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{asset('assets/css/font-awesome.min.css')}}">
    <link rel="stylesheet" href="{{asset('assets/css/custom.min.css')}}">
    <link rel="stylesheet" href="{{asset('assets/css/pnotify.custom.min.css')}}">
  </head>

  <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        <div class="col-md-3 left_col">
          <div class="left_col scroll-view">
            <div class="navbar nav_title" style="border: 0;">
              <a href="{{url('administrador')}}" class="site_title"><i class="fa fa-gamepad"></i> <span>Mi Tiendita</span></a>
            </div>

            <div class="clearfix"></div>

            <!-- menu profile quick info -->
            <div class="profile">
              <div class="profile_pic">
                <img src="{{asset('assets/images/goku_perfil.jpg')}}" alt="..." class="img-circle profile_img">
              </div>
              <div class="profile_info">
                <span>Bienvenido</span>
                <h2>John Doe</h2>
              </div>
            </div>
            <!-- /menu profile quick info -->

            <br />

            <!-- sidebar menu -->
            <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
              <div class="menu_section">
                <h3>General</h3>
                <ul class="nav side-menu">
                  <li><a><i class="fa fa-home"></i> Categorias <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="{{url('administrador/categoria')}}">Listar Categorias</a></li>
                      <li><a href="{{url('administrador/categoria/create')}}">Registrar categoria</a></li>
                      
                    </ul>
                  </li>
                </ul>
                <ul class="nav side-menu">
                  <li><a><i class="fa fa-home"></i> Productos <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="{{url('administrador/producto')}}">Listar Productos</a></li>
                      <li><a href="{{url('administrador/producto/create')}}">Registrar producto</a></li>
                      
                    </ul>
                  </li>
                </ul>
              </div>
            </div>
            <!-- /sidebar menu -->

            <!-- /menu footer buttons -->
            <div class="sidebar-footer hidden-small">
              <a data-toggle="tooltip" data-placement="top" title="Settings">
                <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="FullScreen">
                <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="Lock">
                <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="Logout">
                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
              </a>
            </div>
            <!-- /menu footer buttons -->
          </div>
        </div>

        <!-- top navigation -->
        <div class="top_nav">
          <div class="nav_menu">
            <nav class="" role="navigation">
              <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
              </div>

              <ul class="nav navbar-nav navbar-right">
                <li class="">
                  <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    <img src="{{asset('assets/images/goku_perfil.jpg')}}" alt="">John Doe
                    <span class=" fa fa-angle-down"></span>
                  </a>
                  <ul class="dropdown-menu dropdown-usermenu pull-right">
                    <li><a href="{{action('LoginController@logOut')}}"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
                  </ul>
                </li>

              </ul>
            </nav>
          </div>
        </div>
        <!-- /top navigation -->

        <!-- page content -->
        <div class="right_col" role="main">
          @yield('content')
        </div>
        <!-- /page content -->

        <!-- footer content -->
        <footer>
          <div class="pull-right">
            Gentelella - Bootstrap Admin Template by <a href="https://colorlib.com">Colorlib</a>
          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->
      </div>
    </div>
    <script src="{{asset('assets/js/jquery.min.js')}}"></script>
    <script src="{{asset('assets/js/bootstrap.min.js')}}"></script>
    <script src="{{asset('assets/js/custom.min.js')}}"></script>
    <script src="{{asset('assets/js/pnotify.custom.min.js')}}"></script>
    @yield('scripts')
  </body>
</html>